on:
  push:
    branches:
      - main
      - next

  pull_request:
    branches:
      - main
      - next

name: CI
jobs:
  release-please:
    if: github.event_name == 'push' && github.ref_name == 'main'
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          command: manifest
          token: ${{secrets.WORKFLOW_TOKEN}}
          monorepo-tags: true
          extra-files: packages/svelte/package.json
